apiVersion: apps/v1
kind: Deployment
metadata:
  name: marriagehall-backend-deployment
  labels:
    app: marriagehall-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marriagehall-backend
  template:
    metadata:
      labels:
        app: marriagehall-backend
    spec:
      containers:
      - name: marriagehall-backend
        image: marriagehall-backend:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/marriagehall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "saikiran@671"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SERVER_PORT
          value: "8083"
        - name: TZ
          value: "Asia/Kolkata"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/halls
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/halls
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: marriagehall-backend-service
  labels:
    app: marriagehall-backend
spec:
  selector:
    app: marriagehall-backend
  ports:
  - port: 8083
    targetPort: 8083
    nodePort: 30083
  type: NodePort

